mutation:
  alpha_init_mean: 0.45
  alpha_slow_init_mean: 0.82
  content_w_key_mutate_power: 0.3
  content_b_key_init_min: -0.8
  content_b_key_init_max: 0.3
  content_b_key_mutate_power: 0.25
  content_w_query_init_min: 0.8
  content_w_query_init_max: 1.8
  content_w_query_mutate_power: 0.28
  content_b_query_init_min: 1.0
  content_b_query_init_max: 2.2
  content_b_query_mutate_power: 0.25
  content_temperature_init_min: 1.0
  content_temperature_init_max: 2.2
  content_temperature_mutate_power: 0.1
  content_mutate_rate: 0.75
