mutation:
  content_w_query_init_min: 0.4
  content_w_query_init_max: 1.4
  content_w_query_mutate_power: 0.12
  content_b_query_init_min: 0.2
  content_b_query_init_max: 0.9
  content_b_query_mutate_power: 0.1
  content_temperature_init_min: 2.2
  content_temperature_init_max: 3.8
  content_temperature_mutate_power: 0.1
  content_b_match_init_min: -0.1
  content_b_match_init_max: 0.4
  content_b_match_mutate_power: 0.08
  content_mutate_rate: 0.5
